import { cn } from "@/shared/lib/utils"
import Footer from '@/widgets/Footer/footer'
import { Header } from '@/widgets/header'
import type { Metadata } from "next"
import { Lora, Manrope } from "next/font/google"
import "./globals.css"

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
})

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-screen", "antialiased", lora.variable, manrope.variable)}
    >
      <body className="min-h-full">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
